// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdnIYMnxJQ5dXqEOoasLVyq_-9uwX2OrU',
    appId: '1:496911508961:web:60f86ecb7cb7b903c65ea0',
    messagingSenderId: '496911508961',
    projectId: 'spinlock-45f0e',
    authDomain: 'spinlock-45f0e.firebaseapp.com',
    storageBucket: 'spinlock-45f0e.firebasestorage.app',
    measurementId: 'G-ZW7DKQBX88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaIai5SuNvej-OELBa0IBu3NJc9cb6sto',
    appId: '1:496911508961:android:111590b3038ff4fdc65ea0',
    messagingSenderId: '496911508961',
    projectId: 'spinlock-45f0e',
    storageBucket: 'spinlock-45f0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIQMM8P_4SsKEyac3h9RDU0TiUu9JMqck',
    appId: '1:496911508961:ios:fe7a5673e4586ad4c65ea0',
    messagingSenderId: '496911508961',
    projectId: 'spinlock-45f0e',
    storageBucket: 'spinlock-45f0e.firebasestorage.app',
    iosBundleId: 'com.example.computerEngineeringProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIQMM8P_4SsKEyac3h9RDU0TiUu9JMqck',
    appId: '1:496911508961:ios:fe7a5673e4586ad4c65ea0',
    messagingSenderId: '496911508961',
    projectId: 'spinlock-45f0e',
    storageBucket: 'spinlock-45f0e.firebasestorage.app',
    iosBundleId: 'com.example.computerEngineeringProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdnIYMnxJQ5dXqEOoasLVyq_-9uwX2OrU',
    appId: '1:496911508961:web:cb6d0983eade813ac65ea0',
    messagingSenderId: '496911508961',
    projectId: 'spinlock-45f0e',
    authDomain: 'spinlock-45f0e.firebaseapp.com',
    storageBucket: 'spinlock-45f0e.firebasestorage.app',
    measurementId: 'G-S7YXS8QL3H',
  );
}
